//
// <auto-generated>
//     This code was generated by a tool.
//     Def2Pas, version 0.52
//
//     Copyright (C) 1995-2021, Yegor Mialyk. All Rights Reserved.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//

const
  FarUuid: TGUID = '{00000000-0000-0000-0000-000000000000}';
