{***************************************************************************}
{                                                                           }
{ Delphi Runtime Library                                                    }
{                                                                           }
{ <auto-generated>                                                          }
{     This code was generated by a tool.                                    }
{     Def2Pas, version: 0.50                                                }
{     Copyright (C) 1995-2020, Yegor Mialyk. All Rights Reserved.           }
{                                                                           }
{     Changes to this file may cause incorrect behavior and will be lost if }
{     the code is regenerated.                                              }
{ </auto-generated>                                                         }
{                                                                           }
{ Licensed under the MIT License. See LICENSE for details.                  }
{                                                                           }
{***************************************************************************}

const
  NetworkGuid: TGUID = '{773B5051-7C5F-4920-A201-68051C4176A4}';

const
  EMenuGuid: TGUID = '{742910F1-02ED-4542-851F-DEE37C2E13B2}';

const
  ArcliteGuid: TGUID = '{65642111-AA69-4B84-B4B8-9249579EC4FA}';

const
  LuamacroGuid: TGUID = '{4EBBEFC8-2084-4B7F-94C0-692CE136894D}';

const
  NetBoxGuid: TGUID = '{42E4AEB1-A230-44F4-B33C-F195BB654931}';

const
  ProcListGuid: TGUID = '{1E26A927-5135-48C6-88B2-845FB8945484}';

const
  TmpPanelGuid: TGUID = '{B77C964B-E31E-4D4C-8FE5-D6B0C6853E7C}';
