{***************************************************************************}
{                                                                           }
{ Delphi Runtime Library                                                    }
{                                                                           }
{ <auto-generated>                                                          }
{     This code was generated by a tool.                                    }
{     Def2Pas, version: 0.48                                                }
{     Copyright (C) 1995-2019, Yegor Mialyk. All Rights Reserved.           }
{                                                                           }
{     Changes to this file may cause incorrect behavior and will be lost if }
{     the code is regenerated.                                              }
{ </auto-generated>                                                         }
{                                                                           }
{***************************************************************************}

const
  NetworkGuid: TGUID = '{773B5051-7C5F-4920-A201-68051C4176A4}';

const
  EMenuGuid: TGUID = '{742910F1-02ED-4542-851F-DEE37C2E13B2}';

const
  ArcliteGuid: TGUID = '{65642111-AA69-4B84-B4B8-9249579EC4FA}';

const
  LuamacroGuid: TGUID = '{4EBBEFC8-2084-4B7F-94C0-692CE136894D}';

const
  NetBoxGuid: TGUID = '{42E4AEB1-A230-44F4-B33C-F195BB654931}';
